/* eslint-disable */

// Autogenerated at https://app.quicktype.io/ from example request to https://webhook.site/token/{{XDES_EXTERNAL_WEBHOOK_SITE_TOKEN}}/requests
// Do not modiffy by hand

export interface WebhookSiteApiResponse {
    data:        Datum[];
    total:       number;
    perPage:     number;
    currentPage: number;
    isLastPage:  boolean;
    from:        number;
    to:          number;
}

export interface Datum {
    uuid:               string;
    type:               string;
    tokenID:            string;
    teamID:             null;
    ip:                 string;
    country:            string;
    countryCode:        string;
    region:             string;
    city:               string;
    hostname:           string;
    method:             string;
    userAgent:          string;
    content:            string;
    query:              null;
    headers:            Headers;
    url:                string;
    size:               number;
    files:              any[];
    createdAt:          Date;
    updatedAt:          Date;
    sorting:            number;
    customActionOutput: any[];
    customActionErrors: any[];
    time:               number;
}

export interface Headers {
    contentLength:  string[];
    acceptEncoding: string[];
    userAgent:      string[];
    secFetchMode:   string[];
    acceptLanguage: string[];
    accept:         string[];
    contentType:    string[];
    host:           string[];
}
