/**
 * Schema Fetcher Sample
 *
 * This script demonstrates API compatibility for the `/api/dev/schema` endpoint.
 * It fetches data model schemas used by the schema-first API and saves different
 * schema representations to help developers understand the type models in use.
 *
 * **Purpose:**
 * - Verify API schema endpoint availability
 * - Generate reference type definitions for API models
 * - Provide multiple schema formats for different use cases
 *
 * **Output:**
 * Schema files are saved to `{outputFolder}/getSchemas/{type}/{SchemaName}.{ext}`
 *
 * @author Creoox AG
 * @since 2026
 *
 * @example
 * ```bash
 * pnpm sample:getSchemas
 * ```
 */

import { config } from "../utils/config.js";
import fs from "fs/promises";
import path from "path";

/**
 * Available schema models in the API.
 * Each represents a core data structure used by the xeokit data engine.
 */
type SchemaName = "Event" | "JobState" | "Job";

/**
 * Schema representation formats supported by the API.
 *
 * - `json`: JSON Schema format (validation, documentation)
 * - `ts`: TypeScript interfaces generated by json-schema-to-typescript
 * - `ts-quicktype`: TypeScript interfaces generated by quicktype (alternative generator)
 */
type SchemaType = "json" | "ts" | "ts-quicktype";

/**
 * Fetches a schema definition from the API endpoint.
 *
 * @param schemaName - The name of the schema model to retrieve
 * @param schemaType - The format/representation of the schema
 * @returns The schema definition as a string
 * @throws {Error} When the API request fails or returns non-OK status
 *
 * @example
 * ```ts
 * const jobSchema = await getSchema("Job", "json");
 * const eventTypes = await getSchema("Event", "ts");
 * ```
 */
async function getSchema(
  schemaName: SchemaName,
  schemaType: SchemaType,
): Promise<string> {
  const url = `${config.envs.XDES_API_URL}/api/dev/schema?name=${schemaName}&type=${schemaType}`;

  try {
    const response = await fetch(url, {
      method: "GET",
      headers: {
        Authorization: config.computed.authHeader,
      },
    });
    if (!response.ok) {
      throw new Error(`Response status: ${response.status}`);
    }
    const result = await response.text();
    return result;
  } catch (error: unknown) {
    console.error(error);
    throw Error("error_while_api_request");
  }
}

/**
 * Writes a schema definition to a file in the output directory.
 *
 * Files are organized by type and named by schema:
 * `{outputFolder}/getSchemas/{schemaType}/{schemaName}.{ext}`
 *
 * Creates necessary directories automatically if they don't exist.
 *
 * @param schemaName - The name of the schema (used for filename)
 * @param schemaType - The schema format (used for folder organization)
 * @param content - The schema content to write
 *
 * @example
 * ```ts
 * await writeSchemaToFile("Job", "json", '{"type": "object", ...}');
 * // Creates: output/getSchemas/json/Job.json
 * ```
 */
async function writeSchemaToFile(
  schemaName: SchemaName,
  schemaType: SchemaType,
  content: string,
) {
  const fileExtension = schemaType === "json" ? "json" : "ts";
  const filePath = `${config.fixed.sampleOutputFolder}/getSchemas/${schemaType}/${schemaName}.${fileExtension}`;
  const dir = path.dirname(filePath);
  await fs.mkdir(dir, { recursive: true });
  console.info("Creating file", filePath);

  // Format JSON schemas with 2-space indentation
  const formattedContent =
    schemaType === "json"
      ? JSON.stringify(JSON.parse(content), null, 2)
      : content;

  await fs.writeFile(filePath, formattedContent);
}

/**
 * Main execution function.
 *
 * Fetches all available schemas in all supported formats and saves them to files.
 * This generates a complete reference library of API data models.
 *
 * **Process:**
 * 1. Iterates through all schema types (json, ts, ts-quicktype)
 * 2. For each type, fetches all schema models (Event, Job, JobState)
 * 3. Saves each schema to an organized file structure
 *
 * **Use Cases:**
 * - Verify API is accessible and schemas are available
 * - Generate up-to-date type definitions for development
 * - Compare different schema representations
 * - Document API data models for team reference
 */
async function main() {
  const schemaNames: SchemaName[] = ["Event", "Job", "JobState"];
  const schemaTypes: SchemaType[] = ["json", "ts", "ts-quicktype"];

  for (const schemaType of schemaTypes) {
    for (const schemaName of schemaNames) {
      const content = await getSchema(schemaName, schemaType);
      await writeSchemaToFile(schemaName, schemaType, content);
    }
  }
}

main();
